/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=stats/wrangler.jsonc --include-runtime=false stats/worker-configuration.d.ts` (hash: 689a43b2123deea4d7fc4cb96945a21f)
interface __BaseEnv_Env {
	DB: D1Database;
	GITHUB_OWNER: "srcfl";
	GITHUB_REPOS: "ftw,ftw-webapp,device-drivers";
	SITE_HOSTNAME: "ftw.energy";
	PUBLIC_MIN_REPORTS: "10";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GITHUB_OWNER" | "GITHUB_REPOS" | "SITE_HOSTNAME" | "PUBLIC_MIN_REPORTS">> {}
}
