/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=stats/wrangler.jsonc --include-runtime=false stats/worker-configuration.d.ts` (hash: d67c2f4ef0b8b6f92546f67c3d311a07)
interface __BaseEnv_Env {
	DB: D1Database;
	GITHUB_OWNER: "srcfl";
	GITHUB_REPOS: "ftw,ftw-webapp,device-drivers";
	SITE_HOSTNAME: "app.ftw.energy";
	PUBLIC_MIN_REPORTS: "10";
	CLOUDFLARE_ZONE_ID: "b8e2cf4b19abbeb535cca652750916c9";
	ACCESS_TEAM_DOMAIN: "https://sourceful.cloudflareaccess.com";
	ACCESS_AUD: "980a936eae5215f4484780b68996a4985f435a0e19cd8d11c13225b3f74844cd";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GITHUB_OWNER" | "GITHUB_REPOS" | "SITE_HOSTNAME" | "PUBLIC_MIN_REPORTS" | "CLOUDFLARE_ZONE_ID" | "ACCESS_TEAM_DOMAIN" | "ACCESS_AUD">> {}
}
